#!/bin/bash
# Include the tag, if applicable
outf=build_metadata.h


short=$(git rev-parse HEAD | awk '{print substr($1, 1, 5)}')
cat <<% > $outf
#ifndef _BUILD_METADATA_H_
#define _BUILD_METADATA_H_
/*
  PLEASE NOTE: this file is generated by the $0 script.
     Do not EDIT this file, changes will be lost.
     Do not COMMIT or check this file in, it cannot be version-controlled,
       rather its contents must be derived from git.
*/
#define BUILD_ID "${MY_TAG:-${BUILD_TAG:-0.0.0}}"
#define BUILD_URL "${BUILD_URL:-http://undefined}"
#define BUILD_YEAR "${BUILD_YEAR:-$(date +%Y)}"
#define BUILD_UNAME "${BUILD_UNAME:-$(uname)}"
#define GIT_COMMIT "${GIT_COMMIT:-$(git rev-parse HEAD)}"
#define GIT_COMMIT_SHORT "$short"
#endif
%

